### PR TITLE
Add features to allow users to make appointments by date and time

### PR DESCRIPTION
**Pull request by binlibro**
1. This patch allows a user to book the client by date and time.
2. Delete the appointment requires a username
3. Add a preference settings : MinimumReservationMinutes
4. Delete the field expiration of the table reservations, add two fields begin_time and end_time instead.
   Delete the unique constraint client_id in the table reservations.
5. Modify the cron scripts for allotment calculation
6. Parameter reserve_for  by passing user name changes to the first booking status.
7. Index page adds the date and the time to choose
8. Update the schema of the client and reservation
9. Add js to control the display of time 

The following files are involved:
1. lib/Libki/Controller/API/Client/v1_0.pm:    Modify the client logic.
2. lib/Libki/Controller/API/Public/Reservations.pm:  Add a function for reserve by datetime.
3. lib/Libki/Controller/API/Public/Datatables.pm:      Modification for multiple reservations.
4. lib/Libki/Controller/Administration/API/Datatables.pm Modification for multiple reservations.
5. lib/Libki/Hours.pm b/lib/Libki/Hours.pm:  Modify the calculation of  the minutes and allotment.
6. lib/Libki/Schema/DB/Result/Client.pm: Update the schema.
7. lib/Libki/Schema/DB/Result/Reservation.pm: Update the schema.
8. root/dynamic/templates/administration/settings/index.tt: 
            a.Add a preference MinimumReservationMinutes ,
            b.Modify the text of preference ReservationShowUsername.
            c.Add a new tab for managing reservations.
9. root/dynamic/templates/public/index.tt b/root/dynamic/templates/public/index.tt Add a calendar
10. script/cronjobs/libki.pl b/script/cronjobs/libki.pl: 
11. installer/versions/3/01-add-fields-for-reservation.sql:  Delete the field expiration of the table reservations, add two fields begin_time and end_time instead.
12. lib/Catalyst/Plugin/LibkiSetting.pm 
13. root/static/js/main.js  Control the display of time

### CODE REVIEW

**Comment by loidor** [comment]
Personally, I think this sounds like a great feature! I'll test it out as soon as I can.

I haven't read through it yet - does it change anything besides adding the possibility to make bookings?

**Comment by loidor** [comment]
A short test later and it seems it's a bit broken. When I press the reserve button,  nothing happens and my log spits this out:

```[2019/07/25 11:37:16] [libki] [ERROR] Caught exception in Libki::Controller::Administration::API::Client->reservation "Can't locate object method "reservation" via package "Libki::Model::DB::Client" at /home/libkki/libki-server/lib/Libki/Controller/Administration/API/Client.pm line 118."```

Have a look at that and I'll review it again.

**Comment by binlibro** [comment]
> A short test later and it seems it's a bit broken. When I press the reserve button, nothing happens and my log spits this out:
> 
> `[2019/07/25 11:37:16] [libki] [ERROR] Caught exception in Libki::Controller::Administration::API::Client->reservation "Can't locate object method "reservation" via package "Libki::Model::DB::Client" at /home/libkki/libki-server/lib/Libki/Controller/Administration/API/Client.pm line 118."`
> 
> Have a look at that and I'll review it again.
> 
> Also, the installer was unfortunately a bit broken when you forked - sorry about that. If you want to speed up the setting up of a new server, change `if [ "$is_debian_buster" = true ];` to `elif [ "$is_debian_buster" = true ];` in `install.sh`.

At present, only the client reservation has been completed, and the management part of the backend is under way . If there are no big problems with what I finish now, I'll move on.

**Comment by loidor** [comment]
Ah :) I'll have a second look at it.

**Comment by binlibro** [comment]
> Personally, I think this sounds like a great feature! I'll test it out as soon as I can.
> 
> I haven't read through it yet - does it change anything besides adding the possibility to make bookings?

I didn't change the structure of libki. The libki-client doesn't need to change either.
For the processing of time, 
1. minutes_allotment as available time to the user . 
2. The reservations table stores the time for the reservation
3. The sessions table stores the time for the login. 
4. Reservations are made based on user's available minutes, closing times, other people's reservations, etc.
4. Cancelling the reservation will return the remaining time.
...

**Comment by binlibro** [comment]
> A short test later and it seems it's a bit broken. When I press the reserve button, nothing happens and my log spits this out:
> 
> `[2019/07/25 11:37:16] [libki] [ERROR] Caught exception in Libki::Controller::Administration::API::Client->reservation "Can't locate object method "reservation" via package "Libki::Model::DB::Client" at /home/libkki/libki-server/lib/Libki/Controller/Administration/API/Client.pm line 118."`
> 
> Have a look at that and I'll review it again.
> 
> Also, the installer was unfortunately a bit broken when you forked - sorry about that. If you want to speed up the setting up of a new server, change `if [ "$is_debian_buster" = true ];` to `elif [ "$is_debian_buster" = true ];` in `install.sh`.

The new commit is for the 'Reserve' and 'Cancel' functions of the administration page. There should be no more erros when you click reserve button. I added a cancel button.

**Comment by kylemhall** [comment]
Have you made sure this teacher plays well with the new advanced rules  feature? In the current master of little key to use his allotment is not set for the day until first login time. The reservation link should be set in the sessions tab in the current master of live key to users allotment is not set for the day until first login time. The reservation link should be set in the sessions table.  I haven’t had a chance to review your whole request yet but I will also do so as soon as I can

**Comment by loidor** [comment]
I've looked through it server-side with the client emulator and done just a few tests with an actual client, and I find some issues, some larger, some smaller. So this isn't a full test. I haven't looked at the code at all at this point.

- It doesn't install on Ubuntu 18.04. For some reason it can't drop client_id. I haven't tested it out, but I think it should work with `ALTER TABLE reservations DROP FOREIGN KEY reservations_ibfk_1;` (or what its name really is).

- There's a couple of minor spelling errors in the messages. A couple of double period mark and "chose" is misspelled a couple of times.

- When "First come, first served" is set, the message says the client is closed for the day in the admin area. 

- When reserving, the date field is empty and the hours field doesn't contain all hours - would it be possible to reuse "Add closing hours for specific dates"? That would give it a uniform design as well. I'm asking for this since the patron wouldn't know what that empty square means. 

- I'm a bit confused about the new settings. First, under "Display the status of the first reservation within an hour". I just get this to work within 15 minutes, and I think it would be good to have it for longer time than one hour - in a university library, for example, one hour isn't really that much time. Same part, I'm not sure about combining this setting with the show username setting. I think it would be good to have these as separate settings, since you might like one of them but not the other. I believe though that the status of the reservation always should be presented. Otherwise it's possible for patrons to sit down five minutes before the reserved time and get kicked out pretty immediately, which more than likely would annoy them.

- Also settings - there's a new setting under "Client behavior" that I don't understand what it does. I just noticed it breaks things if it's set to more than the users' available time.

- When reserving, if the date isn't filled out, it doesn't really say anything exept not working. The reserve button gets greyed out, but it's still possible to reserve with enter. It gives a [FATAL] and one [ERROR] in the log.

- All the available user time randomly disappears. First it happened while testing out on a emulated client, so the user was never logged in. This was when I edited the setting under "Client behavior". I wasn't able to reproduce it. When I tested it on an actual client it happened while the user was logged in with less than session minutes left - i.e. when the daily minutes is 0 and there's only time in session minutes. It seemed a bit random and didn't occur at any specific time point.

- I guess these can be more of a next step, but feature wishes:
  - Grey out passed time. Right now it looks like I can reserve a client in passed time.
  - There's not really a need to fill in the username when removing a reservation in the admin area.
  - I'd like to see at what time a client is reserved in both the public and the admin area. Right now I can make a reservation in 2021 and it just says the username.

All in all, I really like the idea. I'm not entirely convinced about removing the possibility to reserve one as soon as it's free, but I think that setting up "as soon as possible" would be somewhat easy to develop. 

However, I think you should test it out much more. Try every possible possibility this could be used and misused - what inexperienced staff might do and question as well as what inexperienced, stressed or malicious patrons might try. Test out every scenario when it comes to installing, configuring and using. Take notes on what might be hard to understand, what doesn't work exactly as planned or what might be minor annoyances.

**Comment by binlibro** [comment]
@loidor Thank you for such a detailed test and these valuable advices. I will try my best to improve it. Obviously, I still have some unconsidered questions that need to be rethought, and I need to test as much as possible to improve. I will submit it again after further improvement. Your advices help me a lot. Thank you so much!

And I also encountered the problem when I tried to drop the unique key client_id when the foreign key exists.
My solution is : "SET FOREIGN_KEY_CHECKS=0" before drop the key. Change it back to "SET FOREIGN_KEY_CHECKS=1" after the drop is finished.  It's in installer/versions/2.05.00.00/01-add-fields-for-reservation.sql

**Comment by binlibro** [comment]
> Have you made sure this teacher plays well with the new advanced rules feature? In the current master of little key to use his allotment is not set for the day until first login time. The reservation link should be set in the sessions tab in the current master of live key to users allotment is not set for the day until first login time. The reservation link should be set in the sessions table. I haven’t had a chance to review your whole request yet but I will also do so as soon as I can

I think it only adds time choices, but no more new advanced rules. 
Most of the added code is a check on the validity of the reservation. Time-based reservations require time allocation. I have to make some changes to the initialization of allotment. I will check the process and logic of allocation of allotment again to make sure there are no conflicts.

**Comment by loidor** [comment]
@binlibro I'll have a look at the db installer - I just noticed it failed on Ubuntu 18.04. I _think_ you have to have both SET FOREIGN_KEY_CHECKS and DROP FOREIGN KEY. Debian 9, 10 and Ubuntu 18.04 all use different versions of Mysql or MariaDB, so it's a bit of a hassle sometimes getting things to work flawlessly on all three.

**Comment by kylemhall** [comment]
> > Have you made sure this teacher plays well with the new advanced rules feature? In the current master of little key to use his allotment is not set for the day until first login time. The reservation link should be set in the sessions tab in the current master of live key to users allotment is not set for the day until first login time. The reservation link should be set in the sessions table. I haven’t had a chance to review your whole request yet but I will also do so as soon as I can
> 
> I think it only adds time choices, but no more new advanced rules.
> Most of the added code is a check on the validity of the reservation. Time-based reservations require time allocation. I have to make some changes to the initialization of allotment. I will check the process and logic of allocation of allotment again to make sure there are no conflicts.

Excellent! They key change is, like I wrote, that daily minutes are not allotted until the first login of the day for each patron. And more importantly, session minutes are not allotted until login time for each and every session. In master, minutes are not "moved" between daily and session minutes as they used to. Instead, they both count down. The rules tell us how long a session is, and then move sets of minutes count down until the session allotment reaches zero.

**Comment by loidor** [comment]
Right, now I've checked the db installer, and the following fixes the Ubuntu 18.04 install issue. This way you delete the foreign key rather than disabling the check (since that for some reason didn't work on Ubuntu 18.04). So use this instead and that part is good to go :)
 
```
ALTER TABLE reservations DROP FOREIGN KEY reservations_ibfk_1; 
ALTER TABLE `reservations`
  ADD `begin_time` datetime,
  ADD `end_time` datetime,
  DROP `expiration`,
  DROP INDEX `client_id`;
INSERT INTO settings SET name='MinimumReservationMinutes', value='5';
```

**Comment by binlibro** [comment]
> Right, now I've checked the db installer, and the following fixes the Ubuntu 18.04 install issue. This way you delete the foreign key rather than disabling the check (since that for some reason didn't work on Ubuntu 18.04). So use this instead and that part is good to go :)
> 
> ```
> ALTER TABLE reservations DROP FOREIGN KEY reservations_ibfk_1; 
> ALTER TABLE `reservations`
>   ADD `begin_time` datetime,
>   ADD `end_time` datetime,
>   DROP `expiration`,
>   DROP INDEX `client_id`;
> INSERT INTO settings SET name='MinimumReservationMinutes', value='5';
> ```

ok,thanks

**Comment by binlibro** [comment]
> When "First come, first served" is set, the message says the client is closed for the day in the admin area, when it's message probably should say something like "Reservations is turned off". Or even better, remove the reserve button when reservations are disabled.
When "First come, first served" is set, the reserve and cancel button are both removed.

> When reserving, the date field is empty and the hours field doesn't contain all hours - would it be possible to reuse "Add closing hours for specific dates"? That would give it a uniform design as well. I'm asking for this since the patron wouldn't know what that empty square means.
Solved.

> I'm a bit confused about the new settings. First, under "Display the status of the first reservation within an hour". I just get this to work within 15 minutes, and I think it would be good to have it for longer time than one hour - in a university library, for example, one hour isn't really that much time. Same part, I'm not sure about combining this setting with the show username setting. I think it would be good to have these as separate settings, since you might like one of them but not the other. I believe though that the status of the reservation always should be presented. Otherwise it's possible for patrons to sit down five minutes before the reserved time and get kicked out pretty immediately, which more than likely would annoy them.
Separating the setting is a better solution, but it needs to modify the libki-client. Using one parameter to display information seems inadequate, and I think this needs further discussion

> Also settings - there's a new setting under "Client behavior" that I don't understand what it does. I just noticed it breaks things if it's set to more than the users' available time.
The new setting means "Minimum reservation time required". I put it under "Reservation setting".

> When reserving, if the date isn't filled out, it doesn't really say anything exept not working. The reserve button gets greyed out, but it's still possible to reserve with enter. It gives a [FATAL] and one [ERROR] in the log.
The date is always not NULL now.

> Grey out passed time. Right now it looks like I can reserve a client in passed time even if I cannot.
Solved.

> There's not really a need to fill in the username when removing a reservation in the admin area
If it has more than one reservation, it can't tell which reservation is which without using the user name.

> I'd like to see at what time a client is reserved in both the public and the admin area. Right now I can make a reservation in 2021 and it just says the username.
I added the time for the first reservation. I think the next step should be add a TAB for manage reservations.
@loidor

**Comment by binlibro** [comment]
> > > Have you made sure this teacher plays well with the new advanced rules feature? In the current master of little key to use his allotment is not set for the day until first login time. The reservation link should be set in the sessions tab in the current master of live key to users allotment is not set for the day until first login time. The reservation link should be set in the sessions table. I haven’t had a chance to review your whole request yet but I will also do so as soon as I can
> > 
> > 
> > I think it only adds time choices, but no more new advanced rules.
> > Most of the added code is a check on the validity of the reservation. Time-based reservations require time allocation. I have to make some changes to the initialization of allotment. I will check the process and logic of allocation of allotment again to make sure there are no conflicts.
> 
> Excellent! They key change is, like I wrote, that daily minutes are not allotted until the first login of the day for each patron. And more importantly, session minutes are not allotted until login time for each and every session. In master, minutes are not "moved" between daily and session minutes as they used to. Instead, they both count down. The rules tell us how long a session is, and then move sets of minutes count down until the session allotment reaches zero.

Now the session minutes and allotment  both count down. When the reservation begin_time is up, the user allotment counts down.And the session minutes will not be allotted until login time for each and every session.

**Comment by binlibro** [comment]
The added functions are moved to lib/Catalyst/Plugin/LibkiSetting.pm In order to reduce the differences with master.

**Comment by loidor** [comment]
I haven't had the time to test this through yet, but will get around to it as soon as some bugs are taken care of :)

**Comment by binlibro** [comment]
> I haven't had the time to test this through yet, but will get around to it as soon as some bugs are taken care of :)

Thank you! :)
I added a new tab for managing reservations in the latest commit.

**Comment by loidor** [comment]
Finally I'll have time to look this over again, so I'll get back to you properly somewhat soon!

**Comment by JSahlberg** [comment]
We (Tidaholms stadsbibliotek / Bibliotek Mellansjö in Sweden) are planning to use Libki for our library and we are really excited about this coming feature! It would be awesome! Great job everyone! :D

**Comment by loidor** [comment]
@binlibro I've finally looked it through and the end product looks great! I haven't found any deal breaking bugs, so I'm as good as ready to merge this.

There's a couple of things we need to change before merging, but it's quite minor things, I think. 
* Convert the db install files to the new format
* Fix the conflicts with the Schema files
* Sync it with the current master

About the converting, it's simply a matter of moving the new sql file to ```installer/versions/3/0.1_add-fields-for-reservations.sql```.

**Comment by JSahlberg** [comment]
@binlibro I've installed your version and I'm getting errors when trying to make an reservation.
The libki.log shows this:
[2019/10/14 10:50:18] [libki] [ERROR] Caught exception in Libki::Controller::Administration::API::DataTables>reservations "Can't locate object method "stringify" via package "DateTime" at /home/libki/libki-server/lib/Libki/Controller/Administration/API/DataTables.pm line 536."

Seems that there is a package missing perhaps?

**Comment by binlibro** [comment]
> @binlibro I've installed your version and I'm getting errors when trying to make an reservation.
> The libki.log shows this:
> [2019/10/14 10:50:18] [libki] [ERROR] Caught exception in Libki::Controller::Administration::API::DataTables>reservations "Can't locate object method "stringify" via package "DateTime" at /home/libki/libki-server/lib/Libki/Controller/Administration/API/DataTables.pm line 536."
> 
> Seems that there is a package missing perhaps?
This is probably a problem with the library. It seems that there is a version problem with package Datetime. I think that reinstalling Datetime through cpan may solve the problem.

**Comment by binlibro** [comment]
@loidor I have completed the following modifications:
1. Convert the db install files to the new format
2. Fix the conflicts with the Schema files
Is there anything else I can do?

**Comment by loidor** [comment]
Great! I didn't get an update about this, so I haven't seen it until now. 

I'll check it once more tomorrow and if everything looks good I'll merge it :)

**Comment by binlibro** [comment]
Thanks a lot! The last commit is a small modification to a potential bug of an error type.

**Comment by JSahlberg** [comment]
I was thinking about the reservations and the opening hours... it seems you can do reservations after closing hours... shouldn't it be relative to the opening hours?

**Comment by binlibro** [comment]
> I was thinking about the reservations and the opening hours... it seems you can do reservations after closing hours... shouldn't it be relative to the opening hours?

Different closing hours can be set for different dates.Although it's today's closing hours, but it does not affect the next day's open hours reservation. I couldn't reproduce the problem yet. Could you tell me your test case that caused the problem?

**Comment by JSahlberg** [comment]
> Different closing hours can be set for different dates.Although it's today's closing hours, but it does not affect the next day's opening hours reservation. I couldn't reproduce the problem yet. Could you tell me your test case that caused the problem?

bild

I've set my opening times for the library to close at 18.00. But I can still do a reservation beyond that time as you can see on the picture i've attached. I think the times available should be matched with the hours the library is open. Do you understand me now? =)

**Comment by binlibro** [comment]
> > Different closing hours can be set for different dates.Although it's today's closing hours, but it does not affect the next day's opening hours reservation. I couldn't reproduce the problem yet. Could you tell me your test case that caused the problem?
> 
> bild
> 
> I've set my opening times for the library to close at 18.00. But I can still do a reservation beyond that time as you can see on the picture i've attached. I think the times available should be matched with the hours the library is open. Do you understand me now? =)

Thanks，I got it. The suggestion is very good and I also thought about it. For now, although we can see the time after closing hours, we couldn't make a reservation successfully and will be prompted with a message.There are some changes that need to be made, and I think improvements to the display will be made in the future.

**Comment by loidor** [comment]
I'm with Bin on this :) 

Anyway, I've checked through it all once more and can't find any deal breaking issues, so I'll merge this!

**Comment by binlibro** [comment]
@loidor Thanks!

**Comment by loidor** [comment]
Travis CI returned failed checks https://travis-ci.org/Libki/libki-server/jobs/600759403

I didn't notice that while merging, so I'll revert this. Sorry about that.

**Comment by binlibro** [comment]
@loidor Sorry,I'll check it.

**Comment by binlibro** [comment]
> Travis CI returned failed checks https://travis-ci.org/Libki/libki-server/jobs/600759403
> 
> I didn't notice that while merging, so I'll revert this. Sorry about that.
@loidor I added missing documentation.Could you try it again with Travis CI? Thanks a lot :)

**Comment by loidor** [comment]
Yeah, you need to make a new PR. You should get a travis check when doing that, so just wait for that to finish. It can take a while, so just give it time and wait for it to turn green.

**Comment by binlibro** [comment]
@loidor https://travis-ci.com/binlibro/libki-server/jobs/248874194 Does that pass？

**Comment by loidor** [comment]
All green - that's perfect!

23 oktober 2019 kl. 22:04, "Bin Wen" <notifications@github.com (mailto:notifications@github.com?to=%22Bin%20Wen%22%20<notifications@github.com>)> skrev:
	@loidor (https://github.com/loidor) https://travis-ci.com/binlibro/libki-server/jobs/248874194 (https://travis-ci.com/binlibro/libki-server/jobs/248874194) Does that pass？

**Comment by binlibro** [comment]
@loidor I tried PR again. But it seems that it can't merge those commits from the first PR again.Only my commits after the merge-revert shows in the new PR. I'm looking for a solution. Maybe the easiest way is to revert the revert, and I make a new PR to correct the error of travis-ci? The changement is very small. What do you think about this ploblem? 
https://stackoverflow.com/questions/19379034/force-merge-after-reverting-merge-commit-int-git

**Comment by loidor** [comment]
I'm sorry, but it's still failing. https://travis-ci.org/Libki/libki-server/jobs/602368413?utm_medium=notification&utm_source=github_status

@kylemhall perhaps you have any idea what's going on? Docker really isn't my cup of tea.

**Comment by binlibro** [comment]
@loidor  It's failed because it needs a small modification in the code, but I don't know how~,    https://github.com/Libki/libki-server/pull/134/files

**Comment by loidor** [comment]
Finally I managed to sort this out. Merged and done!

**Comment by binlibro** [comment]
Thanks a lot!

**Pull request merged**
