### PR TITLE
Creation of restricted areas to login in client using location and category SIP

### PR DESCRIPTION
**Pull request by bouzidfergani**
This feature makes it possible to limit the access to the clients according to the location and the SIP category of the users.
Example: A library organizes its public computers in two locations, Adult and Children, it does not want adults to be able to use children's computers and also children can not use the computers of adults, to do so, just enter the list of categories in each location and Libki will handle this very well for you.
The configuration is done directly in the administration console under client behavior.
Greetings.
Bouzid.

### CODE REVIEW

**Comment by bouzidfergani** [comment]
Hi Kyle,
I resolved conflict for this patch.
This is the test plan:
1- Apply the patch
2- assuming that we have Libki client installed with the following information:
     - node name: node01
     - location: adult
3- start the client for locking with Libki
4- Open the administration console of Libki server and go to: More >> Settings >> Client behavior >> Client log in
5- Note that for each location, there is an input field called:
 List of category authorized to login to clients in location <location>
by default, the value is all to apply no restrictions.
6- When a user connects to Libki using SIP2, the category is always returned in the response (for example in Koha, it is the PC field)
For example:
    users of categories 130,131,132 are classified in adult
    users of categories 150,151 are classified in Children
Example of users: 
    User1 with category 130
    User2 with category 130
    User3 with category 131
    User4 with category 150
    User5 with category 150
7- Fill in the field:
List of category authorized to login to clients in location adult  with the list of categories of adult location (130,131,132)
8- Save the new configuration
9- Connect to node01 client using user User1
10- Success
11- Connect to node01 client using user User4
12- Failure

**Comment by kylemhall** [comment]
@bouzidfergani could you make a pull request to the Libki manual to add documentation for the new feature? I can then merge both the feature and documentation pull requests at the same time.

Thanks!

**Comment by kylemhall** [comment]
@bouzidfergani what's the status of this feature? Do you still want it merged? Can you make a pull request to the manual with a bit of documentation?

**Comment by kylemhall** [comment]
@bouzidfergani I'm going to close this pull request for now. If this is still a feature you want to get into Libki, can you please make a fresh pull request against the latest master branch?

Thanks!

**Pull request closed without merging**
