### PR TITLE
Database update, semantic versioning, bug fix

### PR DESCRIPTION
**Pull request by loidor**
Repost since I messed things up and fixed that mess.

A complete rewrite of the database installation scripts, all merged into one sql file.

The database now has semantic versioning per file!

**How stuff works:**
In installer/versions, there's folders for each major version, i.e. 3. In that folder, we dump the update scripts, i.e. `0.0_initial-database-setup.sql`. update_db.pl reads through every file and concatenates the major version (i.e. the folder name) with the prefix of the update script and thereby creates the complete version number (3.0.0). 

This means that the update script syntax has changed. Instead of being `01-update-name.sql` it's now `0.0_update-name.sql`. The underscore marks the point for split() to make its cut.

Just as before it works just fine with both sql and perl files.

We can now simply drop update scripts into the latest major folder, run update_db.pl and everything should be updated and working (in the best of worlds). It's best to keep updates to one file per update, but on the other hand, nothing says you can't increase the versioning with two numbers at one go, so... `¯\_(ツ)_/¯`

**Other changes:**
The database is now defaulted to charset utf8mb4 with the collation utf8mb4_unicode_ci. This means we never need to set charset or collation on a new table or column ever again.

I finally got rid of the pesky `Any::Moose is deprecated` message. Well... I got rid of all STDERR from Libki.pm by routing it to a black hole variable. It shouldn't cause any memory problems, and if we ever want STDERR back for debugging purposes, it's just to delete or comment out those couple of lines.

### CODE REVIEW

**Comment by kylemhall** [comment]
So, it looks like you've merged all the current changes into a single file. Is there any way to upgrade an older database?

**Comment by loidor** [comment]
Exactly.

No, I thought it would be easier with a fresh start. There's so many different versions and I have no idea of which ones are updateable (I just know that some aren't) I figured this would be easier. 

I could probably write something that tries to update the old structure to the new one, but in that case there won't be any guarantee it will work, especially not from older versions. 

The way I've done it when updating (my running server is usually running for a year or so before I update it again) is by taking a mysql dump, installing the database all over again from scratch and then modify the dump so its values fits into the new db. It would be a lot of regex to write to set that up for every one of the 33 different db versions :)

**Comment by kylemhall** [comment]
Indeed!

The only reasonable path I can see is to 
1) Make a release of the Libki server just prior to this commit ( r19.08 ), with an additional db update which would set the db version 3.0.0
2) Add a file to explain *this* version ( let's call it r20.06 ) you need to upgrade to r19.08 and *then* upgrade to r20.06
3) Add references to 2 everywhere that is appropriate.

What do you think?

**Comment by loidor** [comment]
That would be the easiest way, really. 

To do log:

1. I'll post a new PR with the update, making the db the same as 3.0.0 and setting the version number to 3.0.0 as well. 
2. You make that one a release.
3. I'll add a prompt in this PR's `update_db.pl`, making it impossible to update from anything older, with a message on how to go about it.
4. Finally I'll add a section about updating in the manual as well.

**Comment by loidor** [comment]
It's done for release making now :)

**Comment by loidor** [comment]
And now update_db.pl is updated too. It's possible to make a fresh install or updating an existing 3.x install.  

If you try to update from a 2.x install, you'll be given a message that this isn't doable and a short guide on how to go about doing it (wget the release, unzip it and run update_db.pl from there).

I'll write the manual part tomorrow, and this should be good to go!

**Comment by kylemhall** [comment]
Done! Could you add a check in the db updater such that if the database version is less than 3.0.0 the installer will die with the message to upgrade to Libki 19.08 first?

**Comment by kylemhall** [comment]
This may be useful, or not 😁 https://metacpan.org/pod/Version::Dotted::Semantic

**Comment by loidor** [comment]
Too late, it's already written.

I just want to add a couple of extra lines to the installer die message. I added lines on how to update, but I should add some on how to backup first, in case things go south. I mean, if I don't, the user will probably end up here posting issues and I'll have to take care of it then. 

Anyway, it should be done in four hours or so, depending on what other work chores come up.

**Comment by kylemhall** [comment]
Looks better https://metacpan.org/pod/SemVer

**Comment by kylemhall** [comment]
Awesome! I should have known 😁 

That's a good idea, you could include a link to the manual: http://manual.libki.org/v19.08/libki-manual.html#_backup_restoration

**Comment by loidor** [comment]
Hah, yeah - I'm still extremely new in perl (I've just finished reading "Learning Perl" to get a grip on syntax), so modules is still a new concept for me. It's easier for me to build small stuff like this from scratch than reading up on module documentation :)

**Comment by kylemhall** [comment]
I understand. I've been a Perl guy from the start, so using languages that *don't* have a huge easy to access repository of modules feels odd. I think node is probably the closest to Perl in that way.

**Comment by loidor** [comment]
Right, now it's complete and is ready to merge, and we can close a lot of threads :smile: 

I'll start adding update info to the manual next.

**Comment by loidor** [comment]
I'll merge this now, so I can start building on new things.

**Pull request merged**
