### PR TITLE
Add ability to turn off, turn on or restart clients from the interface

### PR DESCRIPTION
**Pull request by maryse-simard**
Add actions in the interface to control power state of the clients from the administration interface. A user can shutdown or restart all or specific clients. Automatic shutdown lets administrators choose to automatically shutdown all of the computers x minutes after closing time.

The computers can also be turned on using the wake on LAN protocol. Options are available in the settings menu to setup the functionality. A list of MAC addresses can be set up to wake all of the computer at once. The ability to wake up single computers, as can be done with shutdown, is not available. Automatic wake up is also possible, but is set as a single time and don't depend on opening times or location.

By default, wake on LAN operates on the local network (with the server and clients belonging to the same network), using the limited broadcast address if no IP address is set in the settings. It is possible to implement it on distant network by forwarding requests to the broadcast address either via port forwarding at the router level or via a forwarding service running on a dedicated machine.
Please see the corresponding patch in the manual for more details about the new settings.

To test shutdown/restart, you need a client with the corresponding patch applied. Buttons to shutdown and restart all or individual clients can be tested and automatic shutdown can be set to turn off all clients after a location's closing time. Either with the button or automatic shutdown, the value of the "Power off action" setting should be respected.

To test waking up the clients, wake on LAN must first be enabled on the client machines. From the server, one can turn on all the computer at once either with the button "Turn on all clients" or automatically at the time given in the "Automatic power on time" setting. The "MAC addresses" setting must be filled for the action to work.

### CODE REVIEW

**Comment by bruzona** [comment]
QUESTION: By “shutdown clients” do you mean just dropping the Libki client (like the backdoor password), or shutting down the PC entirely?

**Comment by maryse-simard** [comment]
It shuts down the PC.

**Comment by bruzona** [comment]
Thank you.   Remotely dropping *just* the client would also be useful, both as a sort of “override” (for when a patron can’t log in for some reason), but also for the ability to more easily drop the client for PC maintenance tasks.

**Comment by kylemhall** [comment]
@bruzona that sounds like it would be a fairly easy addition that could build on this addition. If you haven't yet, that would make a good enhancement request!

**Comment by bruzona** [comment]
We had a weird thing happen today at one of our remote sites.

A customer was unable to login, yet  the Libki administration GUI shows an "active" session on that PC, and time is counting down normally.  BUT - the Libki login screen on the actual PC has not dropped.

We thought that maybe the workstation had been "locked" but the WebGUI generates error "Unable to Unlock"

The "active" decrementing session name is under guest_DEVICENAME. . . .

What would cause Libki server to show an "active" session for a user who is not actually logged in?




Bruce D. Carter
Technical Services Manager
Mohave County Library District
928.692-5744
Bruce.Carter@mohavecounty.us

**Pull request merged**
